### ISSUE TITLE
[SOUTHBOUND] To implement the 0-10V southbound function

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#11]
This function should receive a number between 1..99 and set the correct V value in the OUTPUT 0-10
Returns true / false

This function will be invoked from the API Engine

**Comment by francisjjp** [comment]
Done. The function is called **int dimming (int regulation);** regulation goes from 0 to 100 and it returns 1 if function was executed right, -1 if not.
