### ISSUE TITLE
[Warnings] To remove all the warnings not related with third party libraries

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#15]
It is necessary to remove all the warnings not related with third party libraries (MQTT)
At this moment there (06.06.17) are 33 Warnings,  31 to be removed

![warnings_ecm2m_050617](https://cloud.githubusercontent.com/assets/2856585/26783994/68fdede6-49fb-11e7-90a9-ebbe4b84f941.png)

**Comment by juanra-bascones** [comment]
I have  removed most of the warnings.
In most cases were minor formal changes (pointer castings, etc..).
In the partciular case of the MQTTAPI.c, has some code changes (making the error handling a little more robust)
There remaining are:
- 2 warnings compiling the PAHO library (variables declared and asigned, but not used).
- 8 Init Functions in main, not used anywhere. Maybe there are for future use.
In both cases, fix is trivial (deletions), but I have let them until further decissions.

**Comment by ralcaide** [comment]
Great, 2 things:

- The warnings of the PAHO library should not be removed. It is an external library
- Main warnings should be removed but by @francisjjp . What do you think?
