### ISSUE TITLE
[Southbound] To provide a minimal southbound with at least one function

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#2]
It is necessary to provide a southbound_ec.h and southbounf_ec.c with at least one function that enables the use of the HW.

It is enough for example a function to act over a relay (on / off)

**Comment by sinapseenergia** [comment]
Two files are uploaded:

southbound_ec.h (header file)
southbound_ec.c (development file)

There are only two functions for activation or deactivation some relay.
