### ISSUE TITLE
[MAIN Program] To provide a minimal but functional main in order to demonstrate how should work the FW

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#3]
In order to clarify the behavior of the firmware is necessary to create the squeleton of the main with at least one function in the infinite loop and several comments explaining the behaviour.

It would be great if the main demonstrates how is "getted" a commend when is received

**Comment by sinapseenergia** [comment]
Last commit shows an example of toggling main relay each second. 

M95 function fails now because of hard fault interrupt.
