### ISSUE TITLE
[SOUTHBOUND] To create southbound functions in order to abstract the TCP communications

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#7]
In order to package the features and ease the development is necessary to create four functions (Southbound API) in order to extract to all the complexity related with the TCP communications. These functions are:

- Connect()
- Disconnect()
- Send_TCP(buffer)
- Receive_TCP(buffer)

These functions could use any level 2 protocol (GPRS, WIFI, ETH..) available but should be transparent for the user (level 5, 6, 7) like the MQTT protocol. The MQTT Client #4 will use these functions in order to connect to the broker, send and receive information

**Comment by ralcaide** [comment]
It is necessary to implement something like https://github.com/eclipse/paho.mqtt.embedded-c/blob/master/MQTTPacket/samples/transport.c but using the TCP/IP stack provided by M95

**Comment by sinapseenergia** [comment]
In this case (M2M-CommBoard), just a interfaz is available (GPRS)

As noted:
> These functions could use any level 2 protocol (GPRS, WIFI, ETH..) available but should be transparent for the user (level 5, 6, 7) like the MQTT protocol. The MQTT Client #4 will use these functions in order to connect to the broker, send and receive information

Exactly isn´t is this. This functions implements same transport level (TCP) (We will add in the future UDP functionality in other "same level" library)

So, for TCP side we will need conection parameters to be managed from wrapper (IP, PORT, KEEPALIVE...)

These parameters have to be managed by lower layers depending on HW (GPRS/WIFI/ETH/OTHER)
In each HW these connection parameters have to be managed separately and by a different way 

Actually we can use at lower levels:
* Quectel M95 (GPRS)
* USR WIFI-232 (WIFI/ETH)

But it´s very imporntant that library allows to select another (future) lower layers, so a mechanism like a "Network Layer Definition" have to be defined.

Even we have to consider to use a primary Network Layer and a Backup One (For instance , we can connect to ETH and if is fallen , reconect with GPRS)

So Network_Layer can be setup as:
* M95
* USR_232
* DUAL(M95, USR232)
* OTHER...

This is an implementation proposal, but the important point here is keep in mind this for the library (and the use with other CommHW like EasyNet CommBoard)

**Comment by francisjjp** [comment]
It is going to be uploaded code for wrappers. The incorporated functions does not incorporated keep alive.

**Comment by francisjjp** [comment]
It is going to be uploaded code for wrappers. The incorporated functions does not incorporated keep alive.
